export const users = [
  {
    id: 1,
    first_name: "Chrissie",
    last_name: "Liversidge",
    age: 57,
    active: false,
  },
  { id: 2, first_name: "Bjorn", last_name: "Chidzoy", age: 20, active: false },
  { id: 3, first_name: "Alden", last_name: "Boycott", age: 43, active: false },
  {
    id: 4,
    first_name: "Annecorinne",
    last_name: "Cheley",
    age: 28,
    active: false,
  },
  { id: 5, first_name: "Chevy", last_name: "Coade", age: 49, active: true },
  {
    id: 6,
    first_name: "Margarete",
    last_name: "Plunket",
    age: 49,
    active: true,
  },
  { id: 7, first_name: "Trudy", last_name: "Blodg", age: 20, active: true },
  {
    id: 8,
    first_name: "Rolland",
    last_name: "Downgate",
    age: 52,
    active: true,
  },
  { id: 9, first_name: "Jere", last_name: "Mundall", age: 19, active: false },
  {
    id: 10,
    first_name: "Vasilis",
    last_name: "Leggitt",
    age: 55,
    active: true,
  },
  { id: 11, first_name: "Jessica", last_name: "Takos", age: 48, active: true },
  { id: 12, first_name: "Kayne", last_name: "Kingh", age: 30, active: true },
  {
    id: 13,
    first_name: "Agnola",
    last_name: "Djuricic",
    age: 57,
    active: false,
  },
  { id: 14, first_name: "Nealy", last_name: "Clemmitt", age: 48, active: true },
  {
    id: 15,
    first_name: "Wildon",
    last_name: "Brandone",
    age: 33,
    active: true,
  },
  {
    id: 16,
    first_name: "Eziechiele",
    last_name: "Stachini",
    age: 40,
    active: false,
  },
  { id: 17, first_name: "Renie", last_name: "Lefridge", age: 56, active: true },
  { id: 18, first_name: "Siana", last_name: "Bungey", age: 57, active: true },
  { id: 19, first_name: "Louis", last_name: "Harse", age: 39, active: false },
  {
    id: 20,
    first_name: "Kristen",
    last_name: "Thomlinson",
    age: 44,
    active: true,
  },
  { id: 21, first_name: "Car", last_name: "Nornasell", age: 42, active: true },
  {
    id: 22,
    first_name: "Sheffield",
    last_name: "Hothersall",
    age: 58,
    active: false,
  },
];
